### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by RolfBly** [fvaleur/dmm_util#2]
When running dmm_util info, I get a message saying that there is no DMM connected, but there is. 
I changed this line: 

    #    Dir.glob("/dev/tty.usbserial*").each do |tty_path|

to this, as `/dev/ttyUSB0` is what I get when connecting the meter

    Dir.glob("/dev/ttyUSB*").each do |tty_path|

to no avail. I don't know anything about Ruby. The function  `open_driver()`, as far as I can tell, is not defined anywhere in your code and isn't part of a standard library either, as far as I can tell. 

I would be grateful for any suggestions to troubleshoot. And yes, I am aware this project is from over 10 years ago.

**Comment by N0ury** [comment]
@RolfBly you can take a look at [this](https://github.com/N0ury/dmm_util) and try it.
It is written in python.
It works the same way as @fvaleur dmm_util.
I haven't used it for a while now.
I hope it will help you.

**Comment by RolfBly** [comment]
Many thanks! I will try that. I'm much more familiar with Python, so... 
Cheers!

**Comment by RolfBly** [comment]
The Python version works better for me.
